//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("LessIO")]
[assembly: System.Reflection.AssemblyDescription("A file system I/O library that overcomes limitations of .NET\'s System.IO librarie" +
    "s (such as long path names), aspires to be platform independent, and require les" +
    "s time to learn than System.IO.")]
[assembly: System.Reflection.AssemblyCompany("Scott Willeke")]
[assembly: System.Reflection.AssemblyVersion("0.3.9")]
[assembly: System.Reflection.AssemblyFileVersion("0.3.9")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Scott Willeke ©2016")]


